project_id = "ryoko-cho"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = false

[studio]
enabled = false

[storage]
enabled = true
